import { Frame } from "@/types";

export const FRAMES: Frame[] = [
  {
    id: "cafe-pedir-cafe",
    scenario: "cafe",
    template: "¿Me pones un ___ con ___?",
    english: "Can you get me a ___ with ___?",
    slots: [
      ["café solo", "café con leche", "cortado"],
      ["leche", "hielo", "un poco de leche"],
    ],
    variants: [
      { spanish: "¿Me pones un café solo con hielo?", english: "Can you get me a black coffee with ice?" },
      { spanish: "¿Me pones un cortado con leche?", english: "Can you get me a cortado with milk?" },
      { spanish: "¿Me pones un café con leche con hielo?", english: "Can you get me a coffee with milk with ice?" },
      { spanish: "¿Me pusiste un café solo con hielo?", english: "Did you get me a black coffee with ice?" },
      { spanish: "¿Me ponías un cortado con leche?", english: "Did you use to get me a cortado with milk?" },
      { spanish: "¿Me pusieron un cortado con leche?", english: "Did they get me a cortado with milk?" },
    ],
    tense: "mixed past",
    note: "'Poner' is very common in Spain for 'to serve/get' in bars.",
  },
  {
    id: "cafe-tostada-aceite",
    scenario: "cafe",
    template: "Quiero una tostada con ___ y ___.",
    english: "I want a toast with ___ and ___.",
    slots: [
      ["aceite", "tomate", "mantequilla"],
      ["jamón", "queso", "mermelada"],
    ],
    variants: [
      { spanish: "Quiero una tostada con aceite y jamón.", english: "I want a toast with oil and ham." },
      { spanish: "Quiero una tostada con tomate y queso.", english: "I want a toast with tomato and cheese." },
      { spanish: "Quiero una tostada con mantequilla y mermelada.", english: "I want a toast with butter and jam." },
      { spanish: "Quería una tostada con aceite y jamón.", english: "I wanted a toast with oil and ham." },
      { spanish: "Quería una tostada con tomate y queso.", english: "I wanted a toast with tomato and cheese." },
      { spanish: "Quería una tostada con mantequilla y mermelada.", english: "I wanted a toast with butter and jam." },
    ],
    tense: "mixed past",
    note: "'Quería' is polite for ordering; 'quise' means 'I tried to' — a common trap.",
  },
  {
    id: "cafe-pedir-cuenta",
    scenario: "cafe",
    template: "¿Nos trae la cuenta, ___?",
    english: "Can you bring us the bill, ___?",
    slots: [["por favor", "cuando pueda", "si es tan amable"]],
    variants: [
      { spanish: "¿Nos trae la cuenta, por favor?", english: "Can you bring us the bill, please?" },
      { spanish: "¿Nos trae la cuenta, cuando pueda?", english: "Can you bring us the bill, when you can?" },
      { spanish: "¿Nos trae la cuenta, si es tan amable?", english: "Can you bring us the bill, if you'd be so kind?" },
      { spanish: "¿Nos trajo la cuenta, por favor?", english: "Did you bring us the bill, please?" },
      { spanish: "¿Nos traía la cuenta siempre?", english: "Did you always bring us the bill?" },
      { spanish: "¿Nos trajeron la cuenta?", english: "Did they bring us the bill?" },
    ],
    tense: "mixed past",
    note: "'Traer' is common; 'cuando pueda' is polite.",
  },
  {
    id: "cafe-servilleta-azucar",
    scenario: "cafe",
    template: "¿Me das ___ y ___?",
    english: "Can you give me ___ and ___?",
    slots: [
      ["una servilleta", "un vaso de agua", "una cucharilla"],
      ["un sobre de azúcar", "un poco de leche", "una pajita"],
    ],
    variants: [
      { spanish: "¿Me das una servilleta y un sobre de azúcar?", english: "Can you give me a napkin and a sugar packet?" },
      { spanish: "¿Me das un vaso de agua y un poco de leche?", english: "Can you give me a glass of water and a little milk?" },
      { spanish: "¿Me das una cucharilla y una pajita?", english: "Can you give me a small spoon and a straw?" },
      { spanish: "¿Me diste una servilleta y un sobre de azúcar?", english: "Did you give me a napkin and a sugar packet?" },
      { spanish: "¿Me dabas siempre un vaso de agua?", english: "Did you always give me a glass of water?" },
      { spanish: "¿Me dieron una cucharilla y una pajita?", english: "Did they give me a small spoon and a straw?" },
    ],
    tense: "mixed past",
    note: "Dar is common in Spain for handing things.",
  },
  {
    id: "cafe-preguntar-precio",
    scenario: "cafe",
    template: "¿Cuánto ___ el ___?",
    english: "How much ___ the ___?",
    slots: [
      ["vale", "cuesta", "costaba"],
      ["café con leche", "zumo de naranja", "bocadillo de jamón"],
    ],
    variants: [
      { spanish: "¿Cuánto vale el café con leche?", english: "How much is the coffee with milk?" },
      { spanish: "¿Cuánto cuesta el zumo de naranja?", english: "How much is the orange juice?" },
      { spanish: "¿Cuánto costaba el bocadillo de jamón?", english: "How much was the ham sandwich?" },
      { spanish: "¿Cuánto valía el café con leche?", english: "How much did the coffee with milk cost?" },
      { spanish: "¿Cuánto costó el zumo de naranja?", english: "How much did the orange juice cost?" },
      { spanish: "¿Cuánto valían los bocadillos?", english: "How much were the sandwiches?" },
    ],
    tense: "mixed past",
    note: "'Vale' is very Spain; 'cuesta' is standard.",
  },
  {
    id: "dog-walk-park-que-edad-tiene",
    scenario: "dog-walk-park",
    template: "¿Qué edad tiene ___?",
    english: "How old is ___?",
    slots: [["tu perro", "tu hijo", "tu hija"]],
    variants: [
      { spanish: "¿Qué edad tiene tu perro?", english: "How old is your dog?" },
      { spanish: "¿Qué edad tiene tu hijo?", english: "How old is your son?" },
      { spanish: "¿Qué edad tenía tu perro?", english: "How old was your dog?" },
      { spanish: "¿Qué edad tenía tu hijo?", english: "How old was your son?" },
      { spanish: "¿Qué edad tenía tu hija?", english: "How old was your daughter?" },
      { spanish: "¿Qué edad tenía tu perro cuando lo adoptaste?", english: "How old was your dog when you adopted him?" },
    ],
    tense: "mixed past",
    note: "Use 'tenía' (imperfect) for age at a past time, not 'tuvo'. Common park small talk.",
  },
  {
    id: "dog-walk-park-que-raza-es",
    scenario: "dog-walk-park",
    template: "¿De qué ___ es?",
    english: "What ___ is it?",
    slots: [["raza", "color"]],
    variants: [
      { spanish: "¿De qué raza es?", english: "What breed is it?" },
      { spanish: "¿De qué color es?", english: "What color is it?" },
      { spanish: "¿De qué raza era?", english: "What breed was it?" },
      { spanish: "¿De qué color era?", english: "What color was it?" },
      { spanish: "¿De qué color era antes?", english: "What color was it before?" },
      { spanish: "¿De qué raza era el anterior?", english: "What breed was the previous one?" },
    ],
    tense: "mixed past",
    note: "Common question about dogs. Use 'era' for description.",
  },
  {
    id: "dog-walk-park-se-llama",
    scenario: "dog-walk-park",
    template: "Se llama ___ y tiene ___ años.",
    english: "His name is ___ and he is ___ years old.",
    slots: [
      ["Luna", "Max", "Toby"],
      ["dos", "tres", "cinco"],
    ],
    variants: [
      { spanish: "Se llama Luna y tiene dos años.", english: "His name is Luna and he is two years old." },
      { spanish: "Se llama Max y tiene tres años.", english: "His name is Max and he is three years old." },
      { spanish: "Se llama Toby y tiene cinco años.", english: "His name is Toby and he is five years old." },
      { spanish: "Se llamaba Max y tenía tres años.", english: "His name was Max and he was three years old." },
      { spanish: "Se llamaba Luna y tenía dos años.", english: "Her name was Luna and she was two years old." },
      { spanish: "Se llamaba Toby y tenía cinco años.", english: "His name was Toby and he was five years old." },
    ],
    tense: "mixed past",
    note: "Imperfect ('se llamaba', 'tenía') when talking about a past pet.",
  },
  {
    id: "dog-walk-park-le-gusta-jugar",
    scenario: "dog-walk-park",
    template: "A ___ le gusta ___.",
    english: "___ likes to ___.",
    slots: [
      ["mi perro", "mi hijo", "mi hija"],
      ["jugar con la pelota", "correr", "saltar"],
    ],
    variants: [
      { spanish: "A mi perro le gusta jugar con la pelota.", english: "My dog likes to play with the ball." },
      { spanish: "A mi hijo le gusta correr.", english: "My son likes to run." },
      { spanish: "A mi perro le gustaba jugar con la pelota.", english: "My dog liked to play with the ball." },
      { spanish: "A mi hija le gustaba saltar.", english: "My daughter liked to jump." },
      { spanish: "A mi perro le gustó jugar con la pelota.", english: "My dog liked playing with the ball (that one time)." },
      { spanish: "A mi hijo le gustó correr.", english: "My son liked running (that one time)." },
    ],
    tense: "mixed past",
    note: "Gustaba for habitual past, gustó for a specific instance. Very common in park chats.",
  },
  {
    id: "dog-walk-park-cuando-era-pequeno",
    scenario: "dog-walk-park",
    template: "Cuando ___ era pequeño, ___.",
    english: "When ___ was little, ___.",
    slots: [
      ["mi perro", "mi hijo", "yo"],
      ["siempre quería jugar", "era muy nervioso", "se portaba mal"],
    ],
    variants: [
      { spanish: "Cuando mi perro era pequeño, siempre quería jugar.", english: "When my dog was little, he always wanted to play." },
      { spanish: "Cuando mi hijo era pequeño, era muy nervioso.", english: "When my son was little, he was very nervous." },
      { spanish: "Cuando yo era pequeño, me portaba mal.", english: "When I was little, I misbehaved." },
      { spanish: "Cuando mi hijo era pequeño, se portaba mal.", english: "When my son was little, he misbehaved." },
      { spanish: "Cuando mi perro era pequeño, era muy nervioso.", english: "When my dog was little, he was very nervous." },
      { spanish: "Cuando yo era pequeño, siempre quería jugar.", english: "When I was little, I always wanted to play." },
    ],
    tense: "imperfect",
    note: "Imperfect for background description. 'Cuando + imperfect' triggers imperfect in the other clause.",
  },
  {
    id: "school-parents-recoger-ninos",
    scenario: "school-parents",
    template: "Hoy ___ yo a los niños.",
    english: "Today I ___ the kids.",
    slots: [["recojo", "recogí", "he recogido"]],
    variants: [
      { spanish: "Hoy recojo yo a los niños.", english: "Today I pick up the kids." },
      { spanish: "Hoy he recogido yo a los niños del cole.", english: "Today I (have) picked up the kids from school." },
      { spanish: "Hoy he recogido yo a los niños.", english: "Today I (have) picked up the kids." },
      { spanish: "Hoy recojo yo a los niños, como siempre.", english: "Today I pick up the kids, as always." },
    ],
    tense: "mixed past",
    note: "In Spain 'he recogido' (present perfect) is the natural choice for earlier today.",
  },
  {
    id: "school-parents-reunion-profesora",
    scenario: "school-parents",
    template: "La profesora me ___ que ___ bien.",
    english: "The teacher told me that ___ behaves well.",
    slots: [
      ["dijo", "decía"],
      ["se porta", "se portaba"],
    ],
    variants: [
      { spanish: "La profesora me dijo que se porta bien.", english: "The teacher told me he behaves well." },
      { spanish: "La profesora me decía que se porta bien.", english: "The teacher used to tell me he behaves well." },
      { spanish: "La profesora me dijo que se portaba bien.", english: "The teacher told me he behaved well." },
      { spanish: "La profesora me decía que se portaba bien.", english: "The teacher used to tell me he behaved well." },
    ],
    tense: "mixed past",
    note: "Common at parent-teacher meetings. 'Portarse bien' is standard Spanish.",
  },
  {
    id: "school-parents-deberes",
    scenario: "school-parents",
    template: "¿___ los deberes ___?",
    english: "Did you do the homework ___?",
    slots: [
      ["Has hecho", "Hiciste", "Hacías"],
      ["hoy", "ayer", "ya"],
    ],
    variants: [
      { spanish: "¿Has hecho los deberes hoy?", english: "Have you done the homework today?" },
      { spanish: "¿Hiciste los deberes ayer?", english: "Did you do the homework yesterday?" },
      { spanish: "¿Hiciste los deberes ya?", english: "Did you do the homework yet?" },
      { spanish: "¿Has hecho los deberes ya?", english: "Have you already done the homework?" },
    ],
    tense: "mixed past",
    note: "Use 'has hecho' (present perfect, very common in Spain) for today, 'hiciste' for a specific past day.",
  },
  {
    id: "school-parents-sacar-nota",
    scenario: "school-parents",
    template: "Mi hijo ___ un ___ en el examen.",
    english: "My son got a ___ on the test.",
    slots: [
      ["sacó", "sacaba"],
      ["10", "sobresaliente", "bien"],
    ],
    variants: [
      { spanish: "Mi hijo sacó un 10 en el examen.", english: "My son got a 10 on the test." },
      { spanish: "Mi hijo sacó un sobresaliente en el examen.", english: "My son got an A on the test." },
      { spanish: "Mi hijo sacaba un 10 en el examen.", english: "My son used to get a 10 on the test." },
      { spanish: "Mi hijo sacaba un bien en el examen.", english: "My son used to get a 'good' on the test." },
    ],
    tense: "mixed past",
    note: "Sobresaliente is the top grade in Spain (10). 'Bien' is a passing grade.",
  },
  {
    id: "school-parents-recoger-activity",
    scenario: "school-parents",
    template: "¿A qué hora ___ mañana?",
    english: "What time is the ___ tomorrow?",
    slots: [["es la recogida", "es la extraescolar", "es la reunión"]],
    variants: [
      { spanish: "¿A qué hora es la recogida mañana?", english: "What time is pickup tomorrow?" },
      { spanish: "¿A qué hora es la extraescolar mañana?", english: "What time is the afterschool activity tomorrow?" },
      { spanish: "¿A qué hora es la reunión mañana?", english: "What time is the meeting tomorrow?" },
      { spanish: "¿A qué hora era la reunión ayer?", english: "What time was the meeting yesterday?" },
    ],
    tense: "present",
    note: "Extraescolar is any after-school club/class. Recogida = pickup at school gate.",
  },
  {
    id: "hairdresser-corte-como",
    scenario: "hairdresser",
    template: "Me corto el pelo ___.",
    english: "I get my hair cut ___.",
    slots: [["como siempre", "un poco más corto", "a capas"]],
    variants: [
      { spanish: "Me corto el pelo como siempre.", english: "I get my hair cut as always." },
      { spanish: "Me corté el pelo un poco más corto.", english: "I got my hair cut a little shorter." },
      { spanish: "Me cortaba el pelo a capas.", english: "I used to get my hair cut in layers." },
      { spanish: "Me corto el pelo a capas.", english: "I get my hair cut in layers." },
    ],
    tense: "mixed past",
    note: "Cortarse is reflexive; 'como siempre' is a classic phrase to avoid decisions.",
  },
  {
    id: "hairdresser-flequillo",
    scenario: "hairdresser",
    template: "¿Me dejas el flequillo ___?",
    english: "Can you leave my bangs ___?",
    slots: [["un poco más largo", "igual", "más corto"]],
    variants: [
      { spanish: "¿Me dejas el flequillo un poco más largo?", english: "Can you leave my bangs a little longer?" },
      { spanish: "¿Me dejaste el flequillo igual?", english: "Did you leave my bangs the same?" },
      { spanish: "¿Me dejabas el flequillo más corto?", english: "Did you used to leave my bangs shorter?" },
      { spanish: "¿Me dejas el flequillo más corto?", english: "Can you leave my bangs shorter?" },
    ],
    tense: "mixed past",
    note: "'Dejar' is used for leaving a specific length; flequillo is Spain Spanish.",
  },
  {
    id: "hairdresser-que-tal",
    scenario: "hairdresser",
    template: "¿Qué tal ___ el fin de semana?",
    english: "How was your weekend?",
    slots: [["pasaste", "fue"]],
    variants: [
      { spanish: "¿Qué tal pasaste el fin de semana?", english: "How did you spend the weekend?" },
      { spanish: "¿Qué tal fue el fin de semana?", english: "How was the weekend?" },
      { spanish: "¿Qué tal pasabas los fines de semana?", english: "How did you used to spend weekends?" },
      { spanish: "¿Qué tal lo pasaste el fin de semana?", english: "How did you get on over the weekend?" },
    ],
    tense: "mixed past",
    note: "'Pasaste' is preterite (specific weekend), 'fue' is common small talk.",
  },
  {
    id: "hairdresser-puntas",
    scenario: "hairdresser",
    template: "Solo ___ las puntas, ¿vale?",
    english: "Just trim the ends, okay?",
    slots: [["córtame", "arregla"]],
    variants: [
      { spanish: "Solo córtame las puntas, ¿vale?", english: "Just cut the ends, okay?" },
      { spanish: "Solo arregla las puntas, ¿vale?", english: "Just tidy the ends, okay?" },
      { spanish: "Solo me corté las puntas.", english: "I just had the ends cut." },
      { spanish: "Solo arreglaba las puntas.", english: "I used to just tidy the ends." },
    ],
    tense: "mixed past",
    note: "Imperative is fine here; 'vale' is quintessential Spain. 'Arreglar' is softer than 'cortar'.",
  },
  {
    id: "hairdresser-lavado",
    scenario: "hairdresser",
    template: "¿Me pones ___ en el lavado?",
    english: "Can you put ___ in the wash?",
    slots: [["un poco de acondicionador", "mascarilla", "el champú de menta"]],
    variants: [
      { spanish: "¿Me pones un poco de acondicionador en el lavado?", english: "Can you put some conditioner in the wash?" },
      { spanish: "¿Me pusiste mascarilla en el lavado?", english: "Did you put mask in the wash?" },
      { spanish: "¿Me ponías el champú de menta en el lavado?", english: "Did you used to put the mint shampoo in the wash?" },
      { spanish: "¿Me pones mascarilla en el lavado?", english: "Can you put mask in the wash?" },
    ],
    tense: "mixed past",
    note: "'Poner' used for adding product; 'lavado' is the wash basin. Mascarilla is hair mask, not face mask.",
  },
  {
    id: "doctor-pharmacy-que-tienes",
    scenario: "doctor-pharmacy",
    template: "¿Qué ___ tienes?",
    english: "What ___ do you have?",
    slots: [["síntomas", "molestias", "problemas"]],
    variants: [
      { spanish: "¿Qué síntomas tienes?", english: "What symptoms do you have?" },
      { spanish: "¿Qué molestias tienes?", english: "What discomfort do you have?" },
      { spanish: "¿Qué problemas tienes?", english: "What problems do you have?" },
      { spanish: "¿Qué síntomas tenías ayer?", english: "What symptoms did you have yesterday?" },
    ],
    tense: "present",
    note: "A common opening question from a doctor. 'Tener' is used for symptoms.",
  },
  {
    id: "doctor-pharmacy-te-duele",
    scenario: "doctor-pharmacy",
    template: "¿Te duele ___?",
    english: "Does ___ hurt?",
    slots: [["la cabeza", "la garganta", "la espalda"]],
    variants: [
      { spanish: "¿Te duele la cabeza?", english: "Does your head hurt?" },
      { spanish: "¿Te dolía la garganta ayer?", english: "Did your throat hurt yesterday?" },
      { spanish: "¿Te dolió la espalda anoche?", english: "Did your back hurt last night?" },
      { spanish: "¿Te duele la garganta?", english: "Does your throat hurt?" },
    ],
    tense: "mixed past",
    note: "Use 'doler' like gustar; the body part is the subject. Preterite for sudden, imperfect for ongoing.",
  },
  {
    id: "doctor-pharmacy-toma-esto",
    scenario: "doctor-pharmacy",
    template: "Toma esto ___ veces al día.",
    english: "Take this ___ times a day.",
    slots: [["dos", "tres", "cuatro"]],
    variants: [
      { spanish: "Toma esto dos veces al día.", english: "Take this twice a day." },
      { spanish: "Toma esto tres veces al día.", english: "Take this three times a day." },
      { spanish: "Tomaste esto cuatro veces al día, ¿verdad?", english: "You took this four times a day, right?" },
      { spanish: "Tomabas esto dos veces al día.", english: "You used to take this twice a day." },
    ],
    tense: "mixed past",
    note: "Common dosage instruction. 'Tomar' is 'take' for medication.",
  },
  {
    id: "doctor-pharmacy-hay-que",
    scenario: "doctor-pharmacy",
    template: "Hay que ___ la receta.",
    english: "You have to ___ the prescription.",
    slots: [["renovar", "recoger", "llevar"]],
    variants: [
      { spanish: "Hay que renovar la receta.", english: "You have to renew the prescription." },
      { spanish: "Hay que recoger la receta.", english: "You have to pick up the prescription." },
      { spanish: "Hubo que llevar la receta a la farmacia.", english: "We had to take the prescription to the pharmacy." },
      { spanish: "Había que renovar la receta cada mes.", english: "You had to renew the prescription every month." },
    ],
    tense: "mixed past",
    note: "'Hay que' is impersonal obligation. Preterite 'hubo que' for specific past, imperfect 'había que' for habitual.",
  },
  {
    id: "doctor-pharmacy-me-ha-recetado",
    scenario: "doctor-pharmacy",
    template: "El médico me ha recetado ___.",
    english: "The doctor has prescribed me ___.",
    slots: [["ibuprofeno", "antibióticos", "jarabe para la tos"]],
    variants: [
      { spanish: "El médico me ha recetado ibuprofeno.", english: "The doctor has prescribed me ibuprofen." },
      { spanish: "El médico me ha recetado antibióticos.", english: "The doctor has prescribed me antibiotics." },
      { spanish: "El médico me recetó antibióticos.", english: "The doctor prescribed me antibiotics." },
      { spanish: "El médico me recetaba jarabe para la tos.", english: "The doctor used to prescribe me cough syrup." },
    ],
    tense: "mixed past",
    note: "Present perfect for recent action, preterite for completed past, imperfect for habitual.",
  },
  {
    id: "shopping-precio-de-leche",
    scenario: "shopping",
    template: "¿Cuánto ___ la ___?",
    english: "How much is the ___?",
    slots: [
      ["cuesta", "valía", "costaba"],
      ["leche", "camiseta", "barra de pan"],
    ],
    variants: [
      { spanish: "¿Cuánto cuesta la leche?", english: "How much is the milk?" },
      { spanish: "¿Cuánto cuesta la barra de pan?", english: "How much is the baguette?" },
      { spanish: "¿Cuánto cuesta la camiseta?", english: "How much is the shirt?" },
      { spanish: "¿Cuánto valía la leche ayer?", english: "How much was the milk yesterday?" },
      { spanish: "¿Cuánto costaba la camiseta antes?", english: "How much did the shirt cost before?" },
    ],
    tense: "mixed past",
    note: "'Valer' is common for prices in Spain; 'costar' is also fine.",
  },
  {
    id: "shopping-talla-mas-grande",
    scenario: "shopping",
    template: "¿Tienen esto en una talla más ___?",
    english: "Do you have this in a ___ size?",
    slots: [["grande", "pequeña"]],
    variants: [
      { spanish: "¿Tienen esto en una talla más grande?", english: "Do you have this in a bigger size?" },
      { spanish: "¿Tienen esto en una talla más pequeña?", english: "Do you have this in a smaller size?" },
      { spanish: "¿Tenían esto en una talla más grande ayer?", english: "Did you have this in a bigger size yesterday?" },
      { spanish: "¿Tuvieron esto en una talla más pequeña la semana pasada?", english: "Did you have this in a smaller size last week?" },
    ],
    tense: "mixed past",
    note: "Use 'talla' for clothes, 'número' for shoes. Adjective agrees with 'talla': más grande/pequeña.",
  },
  {
    id: "shopping-devolver-articulo",
    scenario: "shopping",
    template: "Quiero ___ esto, ___ no me ___.",
    english: "I want to ___ this, ___ it doesn't ___ me.",
    slots: [
      ["devolver", "cambiar"],
      ["porque", "ya que"],
      ["gusta", "vale"],
    ],
    variants: [
      { spanish: "Quiero devolver esto, porque no me gusta.", english: "I want to return this, because I don't like it." },
      { spanish: "Quiero cambiar esto, ya que no me vale.", english: "I want to exchange this, since it doesn't fit me." },
      { spanish: "Quería devolver esto, porque no me gustaba.", english: "I wanted to return this, because I didn't like it." },
      { spanish: "Quise cambiar esto, ya que no me valía.", english: "I tried to exchange this, since it didn't fit me." },
    ],
    tense: "mixed past",
    note: "'No me vale' is very common in Spain for 'doesn't fit/suit'.",
  },
  {
    id: "shopping-pagar-en-efectivo",
    scenario: "shopping",
    template: "¿Puedo ___ ___?",
    english: "Can I ___ ___?",
    slots: [
      ["pagar con", "pagar en"],
      ["tarjeta", "efectivo", "Bizum"],
    ],
    variants: [
      { spanish: "¿Puedo pagar con tarjeta?", english: "Can I pay by card?" },
      { spanish: "¿Puedo pagar en efectivo?", english: "Can I pay in cash?" },
      { spanish: "¿Puedo pagar con Bizum?", english: "Can I pay with Bizum?" },
      { spanish: "¿Podía pagar con tarjeta antes?", english: "Could I pay by card before?" },
      { spanish: "¿Pude pagar en efectivo ayer?", english: "Could I pay in cash yesterday?" },
    ],
    tense: "mixed past",
    note: "Bizum is a popular mobile payment in Spain.",
  },
  {
    id: "shopping-precio-final",
    scenario: "shopping",
    template: "¿Me ___ el ___?",
    english: "Can you ___ me ___?",
    slots: [
      ["dices", "pones", "haces"],
      ["precio final", "descuento", "mejor precio"],
    ],
    variants: [
      { spanish: "¿Me dices el precio final?", english: "Can you tell me the final price?" },
      { spanish: "¿Me pones descuento?", english: "Can you give me a discount?" },
      { spanish: "¿Me haces mejor precio?", english: "Can you do a better price?" },
      { spanish: "¿Me dijiste el precio final ayer?", english: "Did you tell me the final price yesterday?" },
      { spanish: "¿Me ponías descuento antes?", english: "Did you give me a discount before?" },
    ],
    tense: "mixed past",
    note: "'Poner descuento' is typical in markets; 'hacer precio' is haggling.",
  },
  {
    id: "neighbors-small-talk-weather-weekend",
    scenario: "neighbors-small-talk",
    template: "¿Qué tal el ___? ¿___ algo este fin de semana?",
    english: "How's the ___? Are you ___ anything this weekend?",
    slots: [
      ["tiempo", "finde", "día"],
      ["haces", "vas a hacer", "planeas hacer"],
    ],
    variants: [
      { spanish: "¿Qué tal el tiempo? ¿Haces algo este fin de semana?", english: "How's the weather? Are you doing anything this weekend?" },
      { spanish: "¿Qué tal el finde? ¿Vas a hacer algo este fin de semana?", english: "How's the weekend? Are you going to do anything this weekend?" },
      { spanish: "¿Qué tal el día? ¿Planeas hacer algo este fin de semana?", english: "How's your day? Are you planning to do anything this weekend?" },
      { spanish: "¿Qué tal el tiempo? ¿Planeabas hacer algo este fin de semana?", english: "How was the weather? Were you planning to do anything this weekend?" },
      { spanish: "¿Qué tal el finde? ¿Hiciste algo el fin de semana pasado?", english: "How was the weekend? Did you do anything last weekend?" },
    ],
    tense: "mixed past",
    note: "Use 'finde' for short, natural speech. Preterite for specific past actions.",
  },
  {
    id: "neighbors-small-talk-menudo-follon",
    scenario: "neighbors-small-talk",
    template: "Vaya, menudo ___ de ___.",
    english: "Wow, what a ___ of ___.",
    slots: [
      ["polvo", "ruido", "follón"],
      ["obra", "fiesta", "corte de luz"],
    ],
    variants: [
      { spanish: "Vaya, menudo polvo de obra.", english: "Wow, what a lot of dust from the construction." },
      { spanish: "Vaya, menudo ruido de fiesta.", english: "Wow, what a noise from a party." },
      { spanish: "Vaya, menudo follón de corte de luz.", english: "Wow, what a mess from a blackout." },
      { spanish: "Vaya, menudo follón hubo con el corte de luz.", english: "Wow, what a mess there was with the blackout." },
      { spanish: "Vaya, menudo ruido hubo de fiesta anoche.", english: "Wow, there was a lot of noise from a party last night." },
    ],
    tense: "mixed past",
    note: "'Follón' is very Spain, informal. Use 'hubo' for specific past events.",
  },
  {
    id: "neighbors-small-talk-holiday-plans",
    scenario: "neighbors-small-talk",
    template: "¿Os quedáis ___ o tenéis pensado ___?",
    english: "Are you staying ___ or are you planning to ___?",
    slots: [
      ["aquí", "en el barrio", "por la zona"],
      ["salir", "viajar", "iros a la playa"],
    ],
    variants: [
      { spanish: "¿Os quedáis aquí o tenéis pensado salir?", english: "Are you staying here or planning to go out?" },
      { spanish: "¿Os quedáis en el barrio o tenéis pensado viajar?", english: "Are you staying in the neighborhood or planning to travel?" },
      { spanish: "¿Os quedáis por la zona o tenéis pensado iros a la playa?", english: "Are you staying in the area or planning to go to the beach?" },
      { spanish: "¿Os quedasteis aquí o teníais pensado salir?", english: "Did you stay here or were you planning to go out?" },
      { spanish: "¿Os quedabais aquí o teníais pensado iros a la playa?", english: "Were you staying here or planning to go to the beach?" },
    ],
    tense: "mixed past",
    note: "Use 'os' for vosotros. 'Teníais pensado' sounds natural for past plans.",
  },
  {
    id: "neighbors-small-talk-new-car",
    scenario: "neighbors-small-talk",
    template: "¡Qué ___ más ___! ¿Cuándo lo has ___?",
    english: "What a ___ ___! When did you ___ it?",
    slots: [
      ["coche", "perro"],
      ["chulo", "bonito", "grande"],
      ["comprado", "recogido", "adoptado"],
    ],
    variants: [
      { spanish: "¡Qué coche más chulo! ¿Cuándo lo has comprado?", english: "What a cool car! When did you buy it?" },
      { spanish: "¡Qué perro más bonito! ¿Cuándo lo has recogido?", english: "What a pretty dog! When did you pick him up?" },
      { spanish: "¡Qué perro más grande! ¿Cuándo lo has adoptado?", english: "What a big dog! When did you adopt it?" },
      { spanish: "¡Qué coche más chulo! ¿Cuándo lo compraste?", english: "What a cool car! When did you buy it?" },
      { spanish: "¡Qué perro más grande! ¿Cuándo lo adoptaste?", english: "What a big dog! When did you adopt it?" },
    ],
    tense: "mixed past",
    note: "Use 'has comprado' for recent (Spain uses perfect). 'Compraste' is fine for specific past.",
  },
  {
    id: "neighbors-small-talk-complaint-noise",
    scenario: "neighbors-small-talk",
    template: "Oye, ¿anoche oíste ___? Menudo ___.",
    english: "Hey, did you hear ___ last night? What a ___.",
    slots: [
      ["un ruido", "una pelea", "la música"],
      ["jaleo", "escándalo", "cacao"],
    ],
    variants: [
      { spanish: "Oye, ¿anoche oíste un ruido? Menudo jaleo.", english: "Hey, did you hear a noise last night? What a racket." },
      { spanish: "Oye, ¿anoche oíste una pelea? Menudo escándalo.", english: "Hey, did you hear a fight last night? What a scandal." },
      { spanish: "Oye, ¿anoche oíste la música? Menudo cacao.", english: "Hey, did you hear the music last night? What a mess." },
      { spanish: "Oye, ¿oíste la música anoche? Menudo jaleo.", english: "Hey, did you hear the music last night? What a racket." },
      { spanish: "Oye, ¿anoche oísteis ruido? Menudo jaleo.", english: "Hey, did you guys hear noise last night? What a racket." },
    ],
    tense: "mixed past",
    note: "'Jaleo' is common Spain. Use 'oísteis' for vosotros. Preterite 'oíste' for a one-off like last night.",
  },
];
