import { TenseEntry } from "@/types";

export const TENSE_ENTRIES: TenseEntry[] = [
  {
    id: "ir-parque-ninos",
    verb: "ir",
    en: "I go to the park with the kids every afternoon.",
    present: "Voy al parque con los niños cada tarde.",
    preterite: "Ayer fui al parque con los niños.",
    imperfect: "Antes iba al parque con los niños todas las tardes.",
    future: "Mañana iré al parque con los niños.",
  },
  {
    id: "ir-trabajo-bici",
    verb: "ir",
    en: "I go to work by bike.",
    present: "Voy al trabajo en bici.",
    preterite: "Ayer fui al trabajo en bici.",
    imperfect: "Antes iba al trabajo en bici todos los días.",
    future: "Mañana iré al trabajo en bici.",
  },
  {
    id: "ir-supermercado-juntos",
    verb: "ir",
    en: "We go to the supermarket together on Saturdays.",
    present: "Vamos al supermercado juntos los sábados.",
    preterite: "El sábado pasado fuimos al supermercado juntos.",
    imperfect: "Antes íbamos al supermercado juntos cada sábado.",
    future: "El próximo sábado iremos al supermercado juntos.",
  },
  {
    id: "hacer-cena-familia",
    verb: "hacer",
    en: "I make dinner for the family.",
    present: "Hago la cena para la familia.",
    preterite: "Ayer hice la cena para la familia.",
    imperfect: "Antes hacía la cena para la familia todos los días.",
    future: "Mañana haré la cena para la familia.",
  },
  {
    id: "hacer-deberes-ninos",
    verb: "hacer",
    en: "The kids do their homework.",
    present: "Los niños hacen los deberes.",
    preterite: "Ayer los niños hicieron los deberes.",
    imperfect: "De pequeños siempre hacían los deberes juntos.",
    future: "Mañana los niños harán los deberes.",
  },
  {
    id: "hacer-cama-despues-desayuno",
    verb: "hacer",
    en: "I make the bed after breakfast.",
    present: "Hago la cama después del desayuno.",
    preterite: "Ayer hice la cama después del desayuno.",
    imperfect: "De pequeña siempre hacía la cama después del desayuno.",
    future: "Mañana haré la cama después del desayuno.",
  },
  {
    id: "estar-enfermo-nino",
    verb: "estar",
    en: "Our son is sick with a fever.",
    present: "Nuestro hijo está enfermo con fiebre.",
    preterite: "Ayer nuestro hijo estuvo enfermo con fiebre.",
    imperfect: "De pequeño, nuestro hijo estaba enfermo con fiebre a menudo.",
    future: "Mañana nuestro hijo estará enfermo con fiebre otra vez, me temo.",
  },
  {
    id: "estar-cansado-trabajo",
    verb: "estar",
    en: "I'm tired after work.",
    present: "Estoy cansada después del trabajo.",
    preterite: "Ayer estuve cansada después del trabajo.",
    imperfect: "Antes siempre estaba cansada después del trabajo.",
    future: "Mañana estaré cansada después del trabajo.",
  },
  {
    id: "estar-feliz-vacaciones",
    verb: "estar",
    en: "The kids are happy because it's vacation.",
    present: "Los niños están contentos porque están de vacaciones.",
    preterite: "Ayer los niños estuvieron contentos porque estaban de vacaciones.",
    imperfect: "Antes los niños siempre estaban contentos cuando estaban de vacaciones.",
    future: "Mañana los niños estarán contentos porque estarán de vacaciones.",
  },
  {
    id: "tener-sueno-manana",
    verb: "tener",
    en: "I'm sleepy in the mornings.",
    present: "Tengo sueño por la mañana.",
    preterite: "Ayer tuve sueño toda la mañana.",
    imperfect: "De pequeña siempre tenía sueño por la mañana.",
    future: "Mañana tendré sueño otra vez.",
  },
  {
    id: "tener-hambre-ninos",
    verb: "tener",
    en: "The kids are hungry after school.",
    present: "Los niños tienen hambre después del cole.",
    preterite: "Ayer los niños tuvieron hambre después del cole.",
    imperfect: "Antes los niños siempre tenían hambre después del cole.",
    future: "Mañana los niños tendrán hambre después del cole.",
  },
  {
    id: "tener-que-hacer-deberes",
    verb: "tener",
    en: "I have to help with homework.",
    present: "Tengo que ayudar con los deberes.",
    preterite: "Ayer tuve que ayudar con los deberes.",
    imperfect: "Antes siempre tenía que ayudar con los deberes.",
    future: "Mañana tendré que ayudar con los deberes.",
  },
  {
    id: "quedarse-en-casa-cine",
    verb: "quedarse",
    en: "I stay home with the kids to watch a movie.",
    present: "Me quedo en casa con los niños para ver una peli.",
    preterite: "Ayer me quedé en casa con los niños para ver una peli.",
    imperfect: "Antes me quedaba en casa con los niños para ver una peli todos los sábados.",
    future: "Mañana me quedaré en casa con los niños para ver una peli.",
  },
  {
    id: "quedarse-sin-leche",
    verb: "quedarse",
    en: "We run out of milk in the middle of breakfast.",
    present: "Nos quedamos sin leche en medio del desayuno.",
    preterite: "Ayer nos quedamos sin leche en medio del desayuno.",
    imperfect: "Siempre nos quedábamos sin leche en medio del desayuno cuando los niños eran pequeños.",
    future: "Mañana nos quedaremos sin leche en medio del desayuno.",
  },
  {
    id: "quedarse-dormido-en-sofa",
    verb: "quedarse",
    en: "The kids fall asleep on the sofa after lunch.",
    present: "Los niños se quedan dormidos en el sofá después de comer.",
    preterite: "Ayer los niños se quedaron dormidos en el sofá después de comer.",
    imperfect: "Antes los niños se quedaban dormidos en el sofá después de comer todos los días.",
    future: "Mañana los niños se quedarán dormidos en el sofá después de comer.",
  },
  {
    id: "poder-jugar-partido",
    verb: "poder",
    en: "I can't go to the match because I'm working.",
    present: "No puedo ir al partido porque trabajo.",
    preterite: "Ayer no pude ir al partido porque trabajé.",
    imperfect: "De pequeña no podía ir al partido porque siempre tenía deberes.",
    future: "Mañana no podré ir al partido porque trabajaré.",
  },
  {
    id: "poder-dormir-siesta",
    verb: "poder",
    en: "The kids can't nap because they're not tired.",
    present: "Los niños no pueden echar la siesta porque no tienen sueño.",
    preterite: "Ayer los niños no pudieron echar la siesta porque no tenían sueño.",
    imperfect: "Antes los niños no podían echar la siesta porque no tenían sueño.",
    future: "Mañana los niños no podrán echar la siesta porque no tendrán sueño.",
  },
  {
    id: "poder-recoger-casa",
    verb: "poder",
    en: "I can't pick up the toys because I'm on the phone.",
    present: "No puedo recoger los juguetes porque estoy al teléfono.",
    preterite: "Ayer no pude recoger los juguetes porque estuve al teléfono.",
    imperfect: "Antes no podía recoger los juguetes porque siempre estaba al teléfono.",
    future: "Mañana no podré recoger los juguetes porque estaré al teléfono.",
  },
  {
    id: "decir-nino-que-viene-cena",
    verb: "decir",
    en: "I tell the kid that dinner is ready.",
    present: "Le digo al niño que la cena está lista.",
    preterite: "Ayer le dije al niño que la cena estaba lista.",
    imperfect: "Antes le decía al niño que la cena estaba lista.",
    future: "Mañana le diré al niño que la cena está lista.",
  },
  {
    id: "decir-que-haga-silencio",
    verb: "decir",
    en: "I tell them to be quiet in the car.",
    present: "Les digo que se callen en el coche.",
    preterite: "Ayer les dije que se callaran en el coche.",
    imperfect: "Antes les decía que se callaran en el coche.",
    future: "Mañana les diré que se callen en el coche.",
  },
  {
    id: "decir-que-no-puedo-ir",
    verb: "decir",
    en: "I tell my friend I can't make it to the park.",
    present: "Le digo a mi amiga que no puedo ir al parque.",
    preterite: "Ayer le dije a mi amiga que no podía ir al parque.",
    imperfect: "Antes le decía a mi amiga que no podía ir al parque.",
    future: "Mañana le diré a mi amiga que no puedo ir al parque.",
  },
  {
    id: "venir-merienda-ninos",
    verb: "venir",
    en: "The kids come home from school for snack.",
    present: "Los niños vienen a casa para la merienda.",
    preterite: "Ayer los niños vinieron a casa para la merienda.",
    imperfect: "De pequeños, los niños siempre venían a casa para la merienda.",
    future: "Mañana los niños vendrán a casa para la merienda.",
  },
  {
    id: "venir-visita-abuela",
    verb: "venir",
    en: "Grandma comes to visit on Sundays.",
    present: "La abuela viene a visitarnos los domingos.",
    preterite: "El domingo pasado la abuela vino a visitarnos.",
    imperfect: "Antes, la abuela venía a visitarnos cada domingo.",
    future: "El próximo domingo la abuela vendrá a visitarnos.",
  },
  {
    id: "venir-urgente-cole",
    verb: "venir",
    en: "I come quickly when the school calls.",
    present: "Vengo rápido cuando llaman del cole.",
    preterite: "Ayer vine rápido cuando llamaron del cole.",
    imperfect: "Antes siempre venía rápido cuando llamaban del cole.",
    future: "Mañana vendré rápido si llaman del cole.",
  },
  {
    id: "ponerse-jersey-en-casa",
    verb: "ponerse",
    en: "I put on my jersey because it's cold in the house.",
    present: "Me pongo el jersey porque hace frío en casa.",
    preterite: "Ayer me puse el jersey porque hacía frío en casa.",
    imperfect: "De pequeña me ponía el jersey siempre que hacía frío en casa.",
    future: "Mañana me pondré el jersey porque hará frío en casa.",
  },
  {
    id: "ponerse-nervioso-examen",
    verb: "ponerse",
    en: "The kids get nervous before an exam.",
    present: "Los niños se ponen nerviosos antes de un examen.",
    preterite: "Ayer los niños se pusieron nerviosos antes del examen.",
    imperfect: "Antes los niños se ponían nerviosos antes de cualquier examen.",
    future: "Mañana los niños se pondrán nerviosos antes del examen.",
  },
  {
    id: "ponerse-bronceado-playa",
    verb: "ponerse",
    en: "We get tanned at the beach in summer.",
    present: "En verano nos ponemos morenos en la playa.",
    preterite: "El verano pasado nos pusimos morenos en la playa.",
    imperfect: "De pequeños nos poníamos morenos en la playa cada verano.",
    future: "El próximo verano nos pondremos morenos en la playa.",
  },
  {
    id: "llevar-ninos-cole",
    verb: "llevar",
    en: "I take the kids to school.",
    present: "Llevo a los niños al cole.",
    preterite: "Ayer llevé a los niños al cole.",
    imperfect: "Antes llevaba yo a los niños al cole.",
    future: "Mañana llevaré a los niños al cole.",
  },
  {
    id: "llevar-paraguas",
    verb: "llevar",
    en: "I carry an umbrella in my bag.",
    present: "Llevo un paraguas en el bolso.",
    preterite: "Ayer llevé un paraguas en el bolso.",
    imperfect: "Siempre llevaba un paraguas en el bolso cuando vivía en Galicia.",
    future: "Mañana llevaré un paraguas en el bolso.",
  },
  {
    id: "llevar-ninos-parque",
    verb: "llevar",
    en: "I take the kids to the park after school.",
    present: "Llevo a los niños al parque después del cole.",
    preterite: "Ayer llevé a los niños al parque después del cole.",
    imperfect: "Cuando eran pequeños, los llevaba al parque cada tarde.",
    future: "Mañana llevaré a los niños al parque después del cole.",
  },
];
